# Generated by Django 5.2.6 on 2026-01-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(db_column='room_number', max_length=10, unique=True, verbose_name='Nomor Kamar')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('booked', 'Terisi'), ('unavailable', 'Tidak Tersedia')], db_column='status', default='available', max_length=20, verbose_name='Status')),
                ('price', models.IntegerField(db_column='price', verbose_name='Harga per Malam')),
            ],
            options={
                'verbose_name': 'Kamar Hotel',
                'verbose_name_plural': 'Daftar Kamar',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Laporan Harian'), ('monthly', 'Laporan Bulanan'), ('guest_list', 'Daftar Tamu')], db_column='report_type', max_length=20, verbose_name='Jenis Laporan')),
                ('date_from', models.DateField(db_column='date_from', verbose_name='Dari Tanggal')),
                ('date_to', models.DateField(db_column='date_to', verbose_name='Sampai Tanggal')),
                ('file_path', models.FileField(blank=True, db_column='file_path', null=True, upload_to='reports/', verbose_name='File Laporan')),
                ('total_record', models.IntegerField(db_column='total_record', default=0, verbose_name='Jumlah Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Dibuat Pada')),
                ('generated_by', models.ForeignKey(db_column='generated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Daftar Laporan',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_column='nama', max_length=100, verbose_name='Nama Lengkap')),
                ('phone', models.CharField(db_column='phone', max_length=20, verbose_name='No. Telepon')),
                ('id_card_number', models.CharField(db_column='id_card_number', max_length=50, verbose_name='NIK/No. Identitas')),
                ('check_in', models.DateTimeField(auto_now_add=True, db_column='check_in', verbose_name='Waktu Check-In')),
                ('check_in_date', models.DateField(auto_now_add=True, db_column='check_in_date', verbose_name='Tanggal Check-In')),
                ('check_out', models.DateTimeField(blank=True, db_column='check_out', null=True, verbose_name='Waktu Check-Out')),
                ('check_out_date', models.DateField(blank=True, db_column='check_out_date', null=True, verbose_name='Tanggal Check-Out')),
                ('total_price', models.IntegerField(db_column='total_price', default=0, verbose_name='Total Pembayaran')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Kamar')),
            ],
            options={
                'verbose_name': 'Data Tamu',
                'verbose_name_plural': 'Daftar Tamu',
                'db_table': 'guests',
                'ordering': ['-check_in'],
            },
        ),
    ]
