# Generated by Django 5.2.6 on 2026-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_path',
        ),
        migrations.AddField(
            model_name='report',
            name='total_guests',
            field=models.IntegerField(default=0, verbose_name='Jumlah Tamu'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_revenue',
            field=models.IntegerField(default=0, verbose_name='Total Pendapatan (Rp)'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_rooms_occupied',
            field=models.IntegerField(default=0, verbose_name='Kamar Terisi'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Check-In'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_in_date',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal Check-In'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Check-Out'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Check-Out'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id_card_number',
            field=models.CharField(max_length=50, verbose_name='NIK/No. Identitas'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='No. Telepon'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Pembayaran'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(verbose_name='Dari Tanggal'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(verbose_name='Sampai Tanggal'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Laporan Harian'), ('monthly', 'Laporan Bulanan'), ('guest_list', 'Daftar Tamu')], max_length=20, verbose_name='Jenis Laporan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_record',
            field=models.IntegerField(default=0, verbose_name='Jumlah Data'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(verbose_name='Harga per Malam'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Nomor Kamar'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('booked', 'Terisi'), ('unavailable', 'Tidak Tersedia')], default='available', max_length=20),
        ),
    ]
