# Generated by Django 6.0 on 2026-01-22 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_report_file_path_report_total_guests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Tanggal Check-In'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Waktu Check-Out'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nama',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nama Lengkap'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['check_in_date', 'room'], name='idx_checkin_room'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['-check_in'], name='idx_checkin_desc'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['check_out', 'room'], name='idx_checkout_room'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-created_at'], name='idx_report_created'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['date_from', 'date_to'], name='idx_report_period'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'created_at'], name='idx_report_type_date'),
        ),
    ]
