# Generated by Django 5.2.6 on 2026-03-30 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_guest_check_in_date_alter_guest_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out_date',
            field=models.DateField(default=datetime.date(2026, 3, 30)),
            preserve_default=False,
        ),
    ]
