# Generated by Django 5.2.6 on 2026-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_guest_check_in_date_alter_guest_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
