# Generated by Django 5.2.6 on 2026-04-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_guest_is_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_checked_in',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
